modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="spirit"
version="${version}"
displayName="Spirit"
authors="Devs: (Lead) CodexAdrian, Ashh/MsRandom1, ThatGravyBoat, ExpensiveKoala, abused_master/moe/pain in my ass, Artists: Kekie6, Shrimp, Facu"
description='''
A Soul Shards inspired mod - Spawn your own mobs with an enhanced mob spawner
'''